/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba;

import prueba.Circumferencia.VistaCircumferencia;
import prueba.Circumferencia.PanelCircumferencia;
import java.awt.Component;
import java.awt.HeadlessException;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JPanel;
import prueba.cuadradro.PanelRectangulo;
import prueba.cuadradro.VistaRectangulo;

/**
 *
 * @author professor
 */
public class vistaEjecuccion extends javax.swing.JFrame {
PanelCircumferencia pC = new PanelCircumferencia(this,0);
PanelRectangulo pR = new PanelRectangulo(this,0,0);
VistaCircumferencia vC;
VistaRectangulo vR;
  
    /**
     * Creates new form vistaPrueba
     */
    public vistaEjecuccion() {
        initComponents();
        //jPanel1.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 1000));
        getContentPane().setLayout(new java.awt.FlowLayout());

        jMenu1.setText("Opciones");

        jMenuItem1.setText("Circumferencia");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Rectangulo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ejecutarCircumferencia(){
       int radio=pC.getRadio();
       int x=50,y=50,diametroX=radio*2,diametroY=radio*2;
       if(vC==null){
        vC= new VistaCircumferencia(x,y,diametroX,diametroY);
        
     
        }else{
           
         vC.setX(x);
         vC.setY(y);
         vC.setDiametroX(diametroX);
         vC.setDiametroY(diametroY);
         
        }
        vC.setSize(1000,1000);
        vC.setVisible(true);
        
        this.getContentPane().add(vC);
        this.pack();
    
    }
    public void ejecutarRectangulo(){
        int xInicial= 50;
        int yInicial=50;
        int base=pR.getBase();
        int altura=pR.getAltura();
        if(vR==null){
            vR=new VistaRectangulo(xInicial,yInicial,base,altura);
        }else{
            vR.setX(xInicial);
            vR.setY(yInicial);
            vR.setBase(base);
            vR.setAltura(altura);

        }
        
        vR.setSize(1000,1000);
        vR.setVisible(true);
        
        this.getContentPane().add(vR);
      
        
        this.pack();
    
    }
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        pC.setSize(1000,1000);
        pC.setVisible(true);
        this.getContentPane().add(pC);
        this.setVisible(true); 
        pR.setVisible(false);
        this.pack();
        if(vR!=null){
            vR.setVisible(false); 
        }
        
        /*if(vC!=null){
         
         this.remove(pC);
         this.remove(vC);
         //vC.setVisible(false);
        
         }
         this.pack();
         
         
         /* int radio=p.getRadio();
        int x=50,y=50,diametroX=radio*2,diametroY=radio*2;
        
        v= new VistaCircumferencia(x,y,diametroX,diametroY);
        v.setVisible(true);
        v.setSize(1000,1000);
        this.getContentPane().add(v);
        p.setVisible(false);
        this.pack();*/
    
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
       //pR.setSize(1000,1000);
       pR.setVisible(true);
       this.getContentPane().add(pR);
       this.setVisible(true); 
       
        /*if(pR!=null){
         this.setVisible(false);
         }*/
        //Remover panel contrario si ta mostrandose
        pC.setVisible(false);
        if(vC!=null){
            vC.setVisible(false);
        }
        /*if(vR!=null){
          
          //this.remove(pC);
          this.remove(vR);
          vR.setVisible(false);
         //vC.setVisible(false);
         }*/
        
        this.pack();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaEjecuccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaEjecuccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaEjecuccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaEjecuccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaEjecuccion().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
