/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba.Circumferencia;

import java.awt.Graphics;
import java.awt.Toolkit;
import javax.swing.DebugGraphics;
import javax.swing.JFrame;
import prueba.vistaEjecuccion;

/**
 *
 * @author professor
 */
public class PanelCircumferencia extends javax.swing.JPanel{

    /**
     * Creates new form PanelCircumferencia
     */
    VistaCircumferencia v = new VistaCircumferencia();
    private int radio;
    private vistaEjecuccion vpp;
    public PanelCircumferencia() {
        initComponents();
        this.setSize(1000,1000);
        
        
    }

    public PanelCircumferencia(vistaEjecuccion frame,int radio) {
        
        initComponents();
        this.setSize(1000,1000);
        this.radio = radio;
        this.vpp= frame;
    }
    
    public int getRadio() {
        return radio;
    }

    public void setRadio(int radio) {
        this.radio = radio;
    }
    
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Radio");

        jButton1.setText("Dibujar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        String text = jTextField1.getText();
        int radio1 = Integer.parseInt(text);
        this.setRadio(radio1);
        
        ///vpp = new vistaPrueba();
        vpp.ejecutarCircumferencia();
        vpp.pack();
        /*int x=50,y=50,diametroX=radio1*2,diametroY=radio1*2;
        v= new VistaCircumferencia(x,y,diametroX,diametroY);
        v.setVisible(true);
        v.setSize(1000,1000);
        this.setVisible(false);*/
        
     
        /*VistaCircumferencia ScreenObject = new VistaCircumferencia();
   
        
        ScreenObject.setVisible(true);*/
        /*Graphics g = new Graphics();
        pintar(g);
        //this.setSize(Toolkit.getDefaultToolkit().getScreenSize());//establece tamaño pantalla de atras(marron)
        //this.setVisible(true);//hace que sea visible*/
        //jPanel1
        
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
